# Generated by Django 5.0.1 on 2024-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agndTell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='telefones',
            name='telefone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
