import "bootstrap/dist/css/bootstrap.min.css";
import MainContainer from '../components/mainContainer'
import Head from 'next/head'
import {notification} from 'antd'

export const metadata = {
  title: 'Agenda Telefonica',
  description: 'Generated by create next app',
}

export default function MyApp({ Component, pageProps }) {
  return(
    <div>
      <MainContainer>
        <Head>
          <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </Head>
        <Component {...pageProps} />
      </MainContainer>
    </div>
  )
}

/*
return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )


*/